name: sprint_v3
description: chat app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: 2.16.0
  cloud_firestore: 4.9.2


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - web/icons/chat.png
    - android/app/src/main/res/mipmap-hdpi/chat.png
